# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
keyboard_layout:
  layout: "sp"
matches:
  # Personal Information
  - trigger: ":name"
    replace: "Máximo Núñez Alarcón"

  - trigger: ":dni"
    replace: "31661375N"

  - trigger: ":address"
    replace: "C/ Encarnación  Fontiveros nº5, 10 E. 29010  Málaga, España."

  - trigger: ":telephone"
    replace: "659353521"

  - trigger: ":email"
    replace: "nmaximo7@gmail.com"

  - trigger: ":cvv"
    replace: "737"

  - trigger: ":bew"
    replace: "Bupparchard Sa-ardchom"

  - trigger: ":bewDetails"
    replace: "3191100142529, 118 m.1 Mittraphap Muaklek 18180 (BarBoss Steak) Saraburi, Thailand. bupparchard@gmail.com. +668 59 286 657"

  - trigger: ":website"
    replace: "https://justtothepoint.com/"

  - trigger: ":localhost"
    replace: "http://localhost:1313/" 
  
  - trigger: ":big"
    replace: "https://justtothepoint.com/maths/bignaughtylist/"

  - trigger: ":fullwebsite"
    replace: "https://justtothepoint.com/, Free resources, bilingual e-books and videos to help your child and your entire family succeed, develop a healthy lifestyle, and have a lot of fun."

  - trigger: ":social"
    replace: "Twitter: @justtothepoint.\nFacebook: https://www.facebook.com/nmaximo7.\nLinkedIn: https://www.linkedin.com/in/justtothepoint"

  - trigger: ":twitter"
    replace: Anawim, \#justtothepoint.

  # Date, Time, and Weather
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%y"

  - trigger: ":time"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%H:%M"

  - trigger: ":now"
    replace: "It's {{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H.%M"


  - trigger: ":weather"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl 'http://wttr.in/?format=3'"


  - trigger: ":ip"
    replace: "{{output}}"
    vars:
       - name: output
         type: shell
         params:
            cmd: "curl 'https://api.ipify.org'"

  # Inserts common HTML and Markdwon elements
  - trigger: ":hr"
    replace: '<hr />'
  - trigger: ":span"
    replace: '<span>$|$</span>'
  - trigger: ":h1"
    replace: '<h1>$|$</h1>'
  - trigger: ":h2"
    replace: '<h2>$|$</h2>'
  - trigger: ":h3"
    replace: '<h3>$|$</h3>'
  - trigger: ":para"
    replace: '<p>$|$</p>'
  - trigger: ":degree"
    replace: '°'
  - trigger: ":composition"
    replace: '∘'
  - trigger: ":and"
    replace: 'Λ'
  - trigger: ":dot"
    replace: '·'
  - trigger: ":plusminus"
    replace: '±'
  - trigger: ":proof"
    replace: '∎'
  - trigger: ":contradiction"
    replace: '⊥'
  - trigger: ":alfa"
    replace: 'α'
  - trigger: ":beta"
    replace: 'β'
  - trigger: ":gamma"
    replace: 'γ'
  - trigger: ":delta"
    replace: 'δ'
  - trigger: ":lambda"
    replace: "λ"
  - trigger: ":epsilon"
    replace: 'ε'
  - trigger: ":mu"
    replace: 'μ'
  - trigger: ":theta"
    replace: 'θ'
  - trigger: ":zeta"
    replace: 'θ'
  - trigger: ":fi"
    replace: "Φ"
  - trigger: ":&fi"
    replace: "φ"
  - trigger: ":sigma"
    replace: "σ"
  - trigger: ":empty"
    replace: "∅"
  - trigger: ":tau"
    replace: "τ"
  - trigger: ":xi"
    replace: "ξ"
  - trigger: ":infinite"
    replace: "∞"
  - trigger: ":normal"
    replace: "◁"
  - trigger: ":approx"
    replace: "≈"
  - trigger: ":sup"
    replace: '<sup>$|$</sup>'
  - trigger: ":sub"
    replace: '<sub>$|$</sub>'
  - trigger: "&sub1"
    replace: '<sub>1</sub>'
  - trigger: "&sub2"
    replace: '<sub>2</sub>'
  - trigger: "&subn"
    replace: '<sub>n</sub>'
  - trigger: "&subi"
    replace: '<sub>i</sub>'
  - trigger: "&subj"
    replace: '<sub>j</sub>'
  - trigger: ":fraction"
    replace: '<sup>$|$</sup>&frasl;<sub></sub>'
  - trigger: ":ltxfr"
    replace: '\frac{}{}'
  - trigger: "&figure"
    replace: "(Refer to Figure i for a visual representation and aid in understanding it)"
  - trigger: ":convert"
    replace: "sh ./convertWebpDropbox.sh /home/nmaximo7/Dropbox/$ 85 $"
  - trigger: ":ltxtext"
    replace: '\text{}' 
  - trigger: ":discriminant"
    replace: 'Δ'
  - trigger: ":ltxex"
    replace: '^{}'
  - trigger: ":ltxbar"
    replace: '\bar '
  - trigger: ":ltxsqrt"
    replace: '\sqrt{}'
  - trigger: ":ltxsum"
    replace: '\sum_{i=0}^\infty i'
  - trigger: ":ltxprod"
    replace: '\prod_{}^{}'
  - trigger: ":ltxl"
    replace: '\lim_{\Delta x \to 0}'
  - trigger: ":ltxfi"
    replace: '\mathbb{F}'
  - trigger: ":ltxd"
    replace: '\Delta x'
  - trigger: ":ltxint"
    replace: '\int f(x)dx'
  - trigger: ":ltxindef"
    replace: '\int_{a}^{b} f(x)dx'
  - trigger: ":ltxev"
    replace: '\bigg|_{a}^{b}'
  - trigger: ":ltxvect"
    replace: '\vec{v}'
  - trigger: ":ltxmatr"
    replace: '$(\begin{smallmatrix}a & 0\\\ 0 & b\end{smallmatrix})$'
  - trigger: ":highlight"
    replace: "{{< highlight \"text\" >}}"
  - trigger: ":greek"
    replace: "α, β, γ, δ, ε, ζ, η, θ, ι, λ, μ, π, Φ, σ, ρ, φ, °, ○, ɫ ψ"
  - trigger: ":maths"
    replace: "∂ Δ ∇ ∀ ∃ ≈ ∞, ≡ ≋ ≆ ~ ⋄ ≈ ≉ ∴ (then) ⊥ ∎ a ≼ b b ≼ a ℕ ℤ ℚ ℝ ℂ ∈ ∉ ∅ # {} [] @ \ |"
  - trigger: ":link"
    replace: "[$|$]()"
    vars:
      - name: "clipboard"
        type: "clipboard"
  - trigger: ":md-link"
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"
  - trigger: ":html-link"
    replace: "<a href=\"{{clipboard}}\" />$|$</a>"
    vars:
      - name: "clipboard"
        type: "clipboard"
  - trigger: ":span"
    replace: '{{< span style="color:red;" text="$|$" >}}'
    vars:
      - name: "clipboard"
        type: "clipboard"

  - trigger: ":image"
    replace: '![image info](./pictures/image.png)'
    vars:
      - name: "clipboard"
        type: "clipboard"



  # Inserts a markdown code block
  - trigger: ":code"
    replace: "```\n$|$\n```"

  - trigger: ":bracket"
    replace: "[]"
  - trigger: ":notequal"
    replace: "≠"
  - trigger: ":forall"
    replace: "∀"
  - trigger: ":exist"
    replace: "∃"
  - trigger: ":in"
    replace: "∈"
  - trigger: ":isnot"
    replace: "∉"
  - trigger: ":greater"
    replace: ">"
  - trigger: ":greatorequal"
    replace: "≥"
  - trigger: ":lessthan"
    replace: "<"
  - trigger: ":lessorequal"
    replace: "≤"
  - trigger: ":then"
    replace: "⇒"
  - trigger: ":iff"
    replace: "↭"
  - trigger: ":related"
    replace: "~"
  - trigger: ":congruent"
    replace: "≡"
  - trigger: ":terminal"
    replace: "user@pc:~$"
  - trigger: ":operator"
    replace: "·≡×⊕≈≉±"
  - trigger: ":curlybracket"
    replace: "{}"
  - trigger: ":all"
    replace: "#{}[]@≠>≥<≤~\\|"
  - trigger: ":tilde"
    replace: "~"
  - trigger: ":arroba"
    replace: "@"
  - trigger: ":hash"
    replace: "#"
  - trigger: ":backslash"
    replace: "\\"
  - trigger: ":function"
    replace: "fΦ: A → B"
  - trigger: "&pi"
    replace: "π"
  - trigger: ":pipe"
    replace: "|"
  - trigger: ":divide"
    replace: "|"
  - trigger: ":notdivide"
    replace: "ɫ"
  - trigger: ":notin"
    replace: "∉"
  - trigger: ":notsubset"
    replace: "⊄"
  - trigger: ":natural"
    replace: "ℕ"
  - trigger: "&integer"
    replace: "ℤ"
  - trigger: ":direct"
    replace: "⊕"
  - trigger: ":real"
    replace: "ℝ"
  - trigger: ":complex"
    replace: "ℂ"
  - trigger: ":rational"
    replace: "ℚ"
  - trigger: "&intersect" 
    replace: "∩"
  - trigger: ":arrow"
    replace: "→"
  - trigger: "&infinite"
    replace: "∞"
  - trigger: ":cross"
    replace: "†"
  - trigger: ":union"
    replace: "∪"
  - trigger: ":isomorphic"
    replace: "≋"
  - trigger: ":iscontained"
    replace: "⊆⊂"
  - trigger: ":contains"
    replace: "⊃⊇"
  - trigger: ":cycle"
    replace: "⟨a⟩"
  - trigger: ":hat"
    replace: "\\hat{\\mathbf{T}}"
  
  # Shell commands
  - trigger: ":edit"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "gedit /home/nmaximo7/.config/espanso/match/base.yml"

  - trigger: ":quote"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "fortune"

  # Quick search
  - trigger: ":duckduckgo"
    replace: "https://duckduckgo.com/?q="
  - trigger: ":wiki"
    replace: "https://en.wikipedia.org/w/?search="
  - trigger: ":youtube"
    replace: "https://youtube.com/results?q=v"
  - trigger: ":google"
    replace: "https://google.com/search?q="
  - trigger: ":myquote"
    replace: "> [Apocalypse](https://justtothepoint.com/en/library/iwantmore/), Anawim, #justtothepoint."
  - trigger: ":prompt"
    replace: "Could you tell me everything that you know about ..., be extensive and include as many solved examples as possible"
  - trigger: ":chatgpt"
    replace: "https://chat.openai.com/" 
  - trigger: ":perplexity"
    replace: "https://www.perplexity.ai/"
  - trigger: "bnl"
    replace: "http://localhost:1313/maths/bignaughtylist/"
  - trigger: ":biography"
    replace: "# Bibliography

{{< alert info>}}

<i class='fas fa-exclamation-triangle'></i> This content is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. {{% /alert %}}

1. [NPTEL-NOC IITM](https://www.youtube.com/@nptel-nociitm9240), Introduction to Galois Theory.

2. Algebra, Second Edition, by Michael Artin.

3. [LibreTexts](https://math.libretexts.org/), Calculus. Abstract and Geometric Algebra, Abstract Algebra: Theory and Applications (Judson).

4. Field and Galois Theory, by Patrick Morandi. Springer.

5. [Michael Penn](https://www.youtube.com/@MichaelPennMath), and [MathMajor](https://www.youtube.com/@mathmajor).

6. Contemporary Abstract Algebra, Joseph, A. Gallian.

7. [YouTube's Andrew Misseldine](https://www.youtube.com/@Misseldine): Calculus. College Algebra and Abstract Algebra.

8. MIT OpenCourseWare [18.01 Single Variable Calculus, Fall 2007](https://www.youtube.com/watch?v=7K1sB05pE0A&list=PL590CCC2BC5AF3BC1) and [18.02 Multivariable Calculus, Fall 2007](https://www.youtube.com/watch?v=PxCxlsl_YwY&list=PL4C4C8A7D06566F38).  

9. [Calculus Early Transcendentals: Differential & Multi-Variable Calculus for Social Sciences](https://www.sfu.ca/math-coursenotes/Math%20157%20Course%20Notes/index-1.html)."
